#!/bin/bash
# =============================================================================
# STEP 1 — Build the sequence-based HMM from the correct seed set
# =============================================================================
#
# BUG FIXED:
#   The original sequence_based.hmm was built from sequence_aln.afa which
#   contains all 211 ok_kunitz_clean sequences — the same proteins used as
#   test positives.  That is 100% data leakage.
#
# CORRECT APPROACH:
#   Use kunitz_true_seeds.fasta (24 ungapped PDB-derived sequences, already
#   generated by fix_seq_seeds.py from pdb_kunitz_nr_clean.ali).
#
# REQUIRES:  hmmer >= 3.1  (hmmbuild)
#            muscle or mafft  (for multiple sequence alignment)
#
# USAGE:  bash step1_build_seq_hmm.sh
# =============================================================================

set -euo pipefail

PROCESSED="Data/Processed"
SEEDS="$PROCESSED/kunitz_true_seeds.fasta"
SEQ_ALN_CORRECT="$PROCESSED/seq_seeds_aln.afa"
SEQ_HMM="$PROCESSED/sequence_based.hmm"

echo "=== STEP 1: Build sequence-based HMM from clean seeds ==="
echo ""

# ── 1a. Verify seed file ──────────────────────────────────────────────────────
if [ ! -f "$SEEDS" ]; then
    echo "ERROR: $SEEDS not found."
    echo "Run Script/fix_seq_seeds.py first."
    exit 1
fi

N_SEEDS=$(grep -c "^>" "$SEEDS")
echo "Seed file: $SEEDS  ($N_SEEDS sequences)"

if [ "$N_SEEDS" -gt 30 ]; then
    echo "ERROR: seed file has $N_SEEDS sequences — expected ~24."
    echo "       Make sure you are using kunitz_true_seeds.fasta (PDB seeds only),"
    echo "       NOT ok_kunitz_clean.fasta or sequence_aln.afa (those contain test data)."
    exit 1
fi

# ── 1b. Align the seeds ───────────────────────────────────────────────────────
echo ""
echo "Aligning seeds..."

if command -v muscle &>/dev/null; then
    MUSCLE_VER=$(muscle -version 2>&1 | head -1 || true)
    echo "Using muscle: $MUSCLE_VER"
    # muscle v5 uses -align / -output; muscle v3/v4 uses -in / -out
    if muscle -align "$SEEDS" -output "$SEQ_ALN_CORRECT" 2>/dev/null; then
        echo "muscle v5 syntax succeeded."
    else
        echo "Falling back to muscle v3 syntax..."
        muscle -in "$SEEDS" -out "$SEQ_ALN_CORRECT"
    fi
elif command -v mafft &>/dev/null; then
    echo "muscle not found — using mafft."
    mafft --auto "$SEEDS" > "$SEQ_ALN_CORRECT"
else
    echo "ERROR: neither muscle nor mafft found in PATH."
    echo "Install with:  conda install -c bioconda muscle"
    exit 1
fi

if [ ! -s "$SEQ_ALN_CORRECT" ]; then
    echo "ERROR: alignment output is empty: $SEQ_ALN_CORRECT"
    exit 1
fi

N_ALN=$(grep -c "^>" "$SEQ_ALN_CORRECT")
echo "Alignment written: $SEQ_ALN_CORRECT  ($N_ALN sequences)"

# ── 1c. Build HMM ─────────────────────────────────────────────────────────────
echo ""
echo "Building sequence HMM with hmmbuild..."

# Use -n (short flag) — older macOS hmmbuild does not accept --name (long form)
hmmbuild -n sequence_based "$SEQ_HMM" "$SEQ_ALN_CORRECT"

if [ ! -s "$SEQ_HMM" ]; then
    echo "ERROR: hmmbuild produced no output."
    exit 1
fi

echo "HMM written: $SEQ_HMM"

# ── 1d. Sanity check ──────────────────────────────────────────────────────────
NSEQ=$(grep "^NSEQ" "$SEQ_HMM" | awk '{print $2}')
LENG=$(grep "^LENG" "$SEQ_HMM" | awk '{print $2}')
echo ""
echo "HMM summary:"
echo "  NSEQ (training sequences): $NSEQ  (expected ~24)"
echo "  LENG (model length):       $LENG  (expected ~55–70 aa)"

if [ "$NSEQ" -gt 30 ]; then
    echo ""
    echo "ERROR: HMM was built from $NSEQ sequences. Re-check your seed file."
    exit 1
fi

echo ""
echo "Step 1 complete. Proceed to: bash step2_build_struct_hmm.sh"
